return {
    "gmail.com",
    "sina.com",
    "sina.cn",
    "qq.com",
    "foxmail.com",
    "sohu.com",
    "126.com",
    "163.com",
    "yeah.net",
    "outlook.com",
    "hotmail.com",
    "msn.com",
    "mail.top",
    "yahoo.com",
    "chinaren.com",
    "tom.com",
    "139.com"
}