// import React from "react";
// import { Typography } from "@material-ui/core";

import Button from "@material-ui/core/Button";
import React from "react";

const EN_LAN = {
  /**
   *  './src/components/App'
   */
  Loading: 'Loading...',
  Reconnecting: 'reconnecting...',
  Mustbenumbe: 'must be number',
  /**
   *  D:\SASS-Workspace\SASS-CH-EN\packages\app-bff\src\components\Common\AlertError'
   */
  OhISee: 'Oh I see',

  /**
   *  /d/SASS-Workspace/SASS-CH-EN/packages/app-bff/src/components/Common/AutoRepeat
   */
  AutoRepeatSettings: 'Auto Repeat Settings',
  Repeatevery: 'Repeat every',
  Day: 'day',
  Week: 'week',
  Month: 'month',
  RepeatOn: 'Repeat On',
  Starts: 'Starts',
  Startss: 'Starts',
  SelectTime: 'Select Time',
  Ends: 'Ends',
  Never: 'Never',
  On: 'On',
  Occurrences: 'occurrences',
  CANCEL: 'CANCEL',
  DONE: 'DONE',


  /**
   * /app-bff/src/components/Common/Confirm
   */
  Cancel: 'Cancel',


  /**
   * /app-bff/src/components/Common/ErrorBoundary
   */
  SomethingwentwrongPlease: 'Something went wrong. Please',
  Refresh: 'refresh',
  Goback: 'go back',

  /**
   * /app-bff/src/components/Common/NumberInput
   */

  Thenumbermustbeaninteger: 'The number must be an integer',
  Thenumbermustbegreaterthanorequalto: 'The number must be greater than or equal to',
  Thenumbermustbelessthanorequalto: 'The number must be less than or equal to',


  /**
   * /app-bff/src/components/Common/OneTime
   */
  OneTimeSettings: 'One Time Settings',
  Startaftersettingscompleted: 'Start after settings completed',


  /**
   * /app-bff/src/components/Common/Uploader
   */
  PleaseUploaafileinoneofthefollowingformats: 'File Error: Please Upload a file in one of the following formats: "csv".',
  OK: 'ok',


  /**
   * /packages/app-bff/src/components/Community
   */
  CommunityR2aiCommunity: 'R2.ai Community - Your Intelligent Partner in AI',
  CommunityUsethesame: 'Use the same product login ID and password to access our AI community for',
  CommunityRich: 'Rich product resources',
  CommunityIndept: 'In-depth case studies',
  CommunityQuotes: 'Quotes from experts',
  Communityscientists: 'Q&A with data scientists',
  CommunityReviews: 'Reviews from users',
  CommunityFirst: 'First to try our products',
  CommunityAfter: 'After product account expires, you can still use the account to acess our community to learn more!',
  CommunityEnter: 'Enter the community',

  /**
   * /app-bff/src/components/Data/Connect
   */
  FromR2L: 'From R2 Learn',
  Warning: 'Warning',
  Continue: 'Continue',
  DataSize: 'Data Size',
  DataLines: 'File Lines',
  FileName: 'File Name',
  FromComp: 'From Computer',
  NoAuthority: 'No authority.',
  ChooseSampleD: 'Choose Sample Data',
  TargetVariable: 'Target Variable',
  SelectSampleData: 'Select a sample data if you don’t have a dataset yet and want to try out the application.',
  FileMustNotExceed: 'File must not exceed',
  Paused: 'Paused',
  Preparingforupload: 'Preparing for upload...',
  Uploadingdata: 'Uploading data...',
  ExtractTransformLoadinprogress: 'Extract-Transform-Load in progress...',
  Perparingfordatabaseconnection: 'Perparing for database connection..',
  DownloadedData: 'Downloaded Data:',
  Rows: 'rows',
  Samplefileerror: 'sample file error, please choose again',
  Pleasechooseadata: 'Please choose a data source to connect.',
  Resume: 'Resume',
  DataSourceDatabase: 'Data Source - Database',
  Thisactionmaywipeoutallofyourprevious: `This action may wipe out all of your previous work (e.g. models).
  Please proceed with caution.`,
  Name: 'Name',
  LoadSampleData: 'Load Sample Data',

  /**
   * /app-bff/src/components/Data/Quality
   */
  Thechangeswillbeappliedintrainingsection: 'Thank you for fixing the issues. The changes will be applied in training section.',
  Yourtargetvariablehaslessthantwouniquevalues: 'Your target variable has less than two unique values. It is recommended that you reselect a target variable or upload new data.',
  Itisrecommendedthatyou: 'It is recommended that you re-select target or upload new data.',
  Yourtargetvariableisempty: 'Your target variable is empty, It is recommended that you reselect a target variable or upload new data.',
  Yourtargetvariablehasmorethantwouniquevalues: 'Your target variable has more than two unique values, which is not suitable for binary classification.',
  Yourtargetvariablehaslessthan: 'Your target variable has less than',
  Uniquevalueswhichisnot: 'unique values, which is not suitable for Regression.',
  Datasizeistoosmall: 'Data size is too small',
  Somedataissueshighlightedincolor: 'Some data issues, highlighted in color, are found. You can fix them by pressing “Edit The Fixes”, or we will fix them automatically.',
  Targetvariablequalitylooksgood: 'Target variable quality looks good!',
  DataTypeMismatch: 'Data Type Mismatch',
  MissingValue: 'Missing Value',
  Outlier: 'Outlier',
  // TargetVariable: 'Target Variable',
  PredictorVariables: 'Predictor Variables',
  HowR2LearnWillFixtheIssues: 'How R2 Learn Will Fix the Issues',
  Error: 'error!!',
  Numerical: 'Numerical',
  Categorical: 'Categorical',
  VariableQualitylooksgood: 'Variable Quality looks good!',
  Foryourwholedataset: 'For your whole dataset, the number of valid data points will be smaller than the recommended minimum 1000',
  LoadaNewDataset: 'Load a New Dataset',
  SomeissuesarefoundR2learnhasgenerated: 'Some issues are found. R2 learn has generated an automatic fixing solution. You can also create your own fixing solution by clicking “Edit The Fixes” button.',
  EditTheFixes: 'Edit The Fixes',
  // DataTypeMismatch: 'Data Type Mismatch',
  // MissingValue: 'Missing Value',
  Summaryofyourdata: 'Summary of your data',
  CleanData: 'Clean Data',
  // DataTypeMismatch: 'Data Type Mismatch',
  DataComposition: 'Data Composition',
  RowsWillBeFixed: 'Rows Will Be Fixed',
  RowsWillBeDeleted: 'Rows Will Be Deleted',
  LoadaBetterDataset: 'Load a Better Dataset',


  /**
   * /app-bff/src/components/Data/Schema
   */
  Ifyourdatadoesnothaveaheader: 'If your data does not have a header, please reload one WITH A HEADER.',
  Pleaseselectavariableasthetargetvariable: 'Please select a variable as the target variable, and unselect the undesirable variables if necessary.',
  UnselectUndesirableVariables: 'Unselect Undesirable Variables',
  Missing: 'Missing',
  Unselectpredictorsthatleadtolesswantedmodeling: 'Unselect predictors that lead to less wanted modeling results, they could be:',
  VariableIDs: '1. Variable IDs',
  Variablesthatarederivedfromthetarget: "2. Any other variables you don't nees",
  Anyothervariablesyou: "",
  DuplicatedHeader: 'Duplicated NormalHeader',
  AutoHeaderRepair: 'Auto NormalHeader Repair',
  SkipDataQualityCheck: 'Skip Data Quality Check',
  Ifyouknowthedataisclean: 'If you know the data is clean, you can skip the data quality step.',


  /**
   * /app-bff/src/components/Data
   */
  DataConnects: 'Data Connect',
  DataSchemas: 'Data Schema',
  DataQualitys: 'Data Quality',


  /**
   * /app-bff/src/components/Deploy
   */
  CreatedDate: 'Created Date',
  DeploymentStatus: 'Deployment Status',
  Home: 'Home',
  SortBy: 'Sorted by',
  ProPerPage: 'Projects per Page',
  ProjectName: 'Project Name',
  Enable: 'Enable',
  ModelName: 'Model Name',
  Owner: 'Owner',
  PerformanceStatus: 'Performance Status',
  Normal: 'Normal',
  Issue: 'Issue',
  IssueS: 'Issue',
  SS: 's',
  Running: 'Running',
  NA: 'N/A',

  /**
   * /app-bff/src/components/Detail
   */
  Deployments: 'Deployment',
  OperationMonitor: 'Operation Monitor',
  PerformanceMonitor: 'Performance Monitor',
  Pleaseuploadafileintheformatofcsv: 'File Error: Please upload a file in the format of "csv".',


  /**
   * /app-bff/src/components/Detail/Deployment
   */
  Model: 'Model',
  DeploymentDataDefinition: 'Deployment Data Definition',
  ValidationDataDefinitionTip: 'It contain variables used for validation. The data source for validation should contain all the variables mentioned in validation data definition.',
  Download: 'Download',
  EmailtoReceiveAlert: 'Email to Receive Alert:',
  Edit: 'Edit',
  Save: 'Save',
  PredictWithAPI: 'Predict with API',
  Or: 'Or',
  APISource: 'API Source',
  PredictWithDataSource: 'Predict with Data Source',
  DataSourceText: 'Data Source',
  LocalFile: 'Local File',
  ResultLocation: 'Result Location:',
  InApp: 'In App',
  DeployFrequency: 'Deploy Frequency',
  OneTime: 'One Time',
  Time: 'time',
  Times: 'time',
  Redeployevery: 'Redeploy every',
  AutoRepeat: 'Auto Repeat',
  Autodisableifanyissueoccurs: 'Auto disable if any issue occurs',
  Introduction: 'Introduction',
  WhatDoesOurAPIDo: 'What does our API do?',
  WhatDoesOurAPIDoAnswer: 'The API serves as an http interface of pre-trained models for user to make predictions. After models are successfully trained, user can consider these model as APIs and make predictions by calling them.',
  Request: 'Request',
  Parameters: 'Parameters',
  ResponseSample: 'Response Sample',
  Authentication: 'Authentication',
  DeploymentAuthentication: 'For each API call, we use an auto-generated token for the authentication. For each deployment of each project a unique token is generated. After an API call using the token corresponding usage will be counted ',
  ErrorCodes: 'Error Codes',
  RateLimit: 'Rate limit',
  DeploymentRateLimit: 'As different limitations are applied to accounts of different levels, when the number/concurency of API calls of user has reached the max allowed amount, subsequent requests will be placed into a request queue as a waiting list. A time-out may be caused if this queue is too long.',
  DeploymentId: 'deploymentId',
  Token: 'token',
  Showtoken: 'show token',
  CURLSample: 'cURL Sample',


  /**
   * /app-bff/src/components/Detail/Operation
   */
  DeploymentTime: 'Deployment Time',
  DeploymentStyle: 'Deployment Style',
  ExecutionSpeed: 'Execution Speed',
  Rowss: '(rows/s)',
  TotalLines: 'Total Lines',
  Status: 'Status',
  Results: 'Results',
  Predictwith: 'Predict with',

  /**
   * app-bff/src/components/Detail/Performance
   */
  MeasurementMetric: 'Measurement Metric',
  AUC: 'AUC',
  Accuracy: 'Accuracy',
  Accuracys: 'Accuracy',
  RMSE: 'RMSE',
  MetricThreshold: 'Metric Threshold',


  /**
   * /app-bff/src/components/Detail/Performance
   */
  NextMonitorDate: 'Next Monitor Date',
  ValidationDataSource: 'Validation Data Source',
  Threshold: 'Threshold',
  ModelInvokeTime: 'Model Invoke Time',
  Performance: 'Performance',
  NoDeploymentReportYet: 'No deployment report yet',


  /**
   * /app-bff/src/components/Home
   */
  CreateProject: 'Create a New Project',
  DeleteDialogTitle: 'Delete project confirmation',
  ConfirmOfDeletManyProject: 'Are you sure to delete the following projects',
  Areyousuretodeleteproject: 'Are you sure to delete project',
  Open: 'OPEN',
  Selected: 'Selected',
  LastCreated: 'Last Created',
  LastModified: 'Last Modified',


  /**
   * /app-bff/src/components/Layout/NormalHeader
   */
  TotalProject: 'Total Project',
  Enabled: 'Enabled',
  Disabled: 'Disabled',
  ChangePassword: 'Change Password',
  LogOut: 'Log Out',
  Notification: 'Notification',
  Welcome: 'Welcome',
  WelcometoR2ai: 'Welcome to R2.ai',
  Problem: 'Problem',
  Project: 'Project',
  Data: 'Data',
  Modeling: 'Modeling',


  /**
   * /app-bff/src/components/Layout/Sider
   */
  Support: 'Support',
  AccountInfo: 'Account Info',
  Training: 'Training',
  TrainingS: 'Training',
  Console: 'Console',


  Dataset: 'Dataset',
  Sorrybutyoudonthavetheauthority: "Sorry but you don't have the authority for entering this project.",
  Youhavebeenkickedout: 'You have been kicked out',
  GoBacktotheProject: 'Go Back to the Project',
  GotoHomePage: 'Go to Home Page',
  Youhavebeenkickedoutof: 'You have been kicked out of the project by another user.',


  // /app-bff/src/components/Modeling
  StartModeling: 'Start Modeling',
  ModelSelection: 'Model Selection',


  // /app-bff/src/components/Modeling/AdvancedView
  Diagnose: 'Diagnose',
  All: 'All',
  ModelNameContains: 'Model Name Contains',
  ModelingResults: 'Modeling Results',
  Givenaparticularpopulation: 'Given a particular population, the accuracy measures the percentage of the correct predictions; For example, for a population of 100 that has 70 yes and 30 no, if the model predicts 60 yes correctly and 20 no correctly, then its accuracy is (60+20)/100 = 80%.',
  Itrepresentsthecompleteness: 'Recall=TP/(TP+FN). It measures the percentage of positives the classifier labeled as positive. It represents the completeness of the classifier. The higher the recall is the more positives the classifier captures.',
  Manyclassifiersareabletoproduce: 'Cutoff Threshold is a critical probability which divides the prediction results into an event group and non-event group. A prediction result that is larger than the threshold goes into the event group, and a prediction result that is smaller than the threshold goes into the non-event group.',
  TheF1scoreistheharmonicmean: 'The F1-score is the harmonic mean of Precision and Recall, where an F1-score reaches its best value at 1 (perfect precision and recall) and worst at 0.',
  PrecisionRecall: "It's 2*Precision*Recall / (Precision+Recall).",
  Itmeasureshowmanytruepositivesamong: 'It measures how many true positives among all predicted (including true and false)  positives. It\'s TP/(TP+FP). From the calculation, one can tell that the bigger the value is the fewer false positive by the classifier. It sort of represents the exactness of the classifier.',
  Efficientwaytodetermine: 'KS = TPR - FPR. KS is an efficient way to determine if two classes are significantly different from each other. It\'s calculated as the maximum of the difference of true positive rate and false positive rate over all thresholds. The higher KS the more distinct one class is from the other.',
  RootMeanSquareError: 'Root Mean Square Error (RMSE) measures prediction errors of the model. Normalized RMSE will help you compare model performance: the smaller the better.',
  R2isastatisticalmeasure: 'R² is a statistical measure of how close the data are to the fitted regression line. R² = Explained variation / Total variation.',
  RootMeanSquareErrorprediction: 'Root Mean Square Error (RMSE) measures prediction errors of the model. Normalized RMSE will help you compare model performance: the smaller the better.',
  RMSLEissimilarwithRMSE: 'RMSLE is similar with RMSE, but use log to y and y_pred first',
  MeanSquaredErro: 'Mean Squared Error',
  MeanAbsoluteError: 'Mean Absolute Error',
  TheadjustedR2tells: 'The adjusted R² tells you the percentage of variation explained by only the independent variables that actually affect the dependent variable.',
  LogLossis: 'Log Loss is -1 * the log of the likelihood function.',
  Thelikelihoodfunctionanswers: 'Likelihood loss or cross-entropy loss estimates the error between the real value and the predicted value: the smaller the better. ',
  F1Score: 'F1-Score',
  Precision: 'Precision',
  Recall: 'Recall',
  LogLoss: 'LogLoss',
  CutoffThreshold: 'Cutoff Threshold',
  KS: 'KS',
  Validation: 'Validation',
  Holdout: 'Holdout',
  NormalizedRMSE: 'Normalized RMSE',
  MSLE: 'MSLE',
  RMSLE: 'RMSLE',
  MSE: 'MSE',
  MAE: 'MAE',
  R2: 'R2',
  AdjustR2: 'AdjustR2',
  ResidualPlotDiagnose: 'Residual Plot Diagnose',
  FitPlot: 'Fit Plot',
  ResidualPlot: 'Residual Plot',
  VariableImpact: 'Variable Impact',
  ROCCurve: 'ROC Curve',
  PredictionDistribution: 'Prediction Distribution',
  PrecisionRecallTradeoff: 'Precision Recall Tradeoff',
  LiftChart: 'Lift Chart',
  GainChart: "Gain Chart",
  KSCurve: "KS Curve",
  Gain: "Gain",
  ModelProcessFlow: 'Model Process Flow',
  Report: 'Report',
  Reset: 'Reset',
  ModelComparisonCharts: 'Model Comparison Charts',
  Close: 'Close',
  RandomlyDistributed: 'Randomly Distributed',
  YaxisUnbalanced: 'Y-axis Unbalanced',
  XaxisUnbalanced: 'X-axis Unbalanced',
  Outliers: 'Outliers',
  Nonlinear: 'Nonlinear',
  Heteroscedasticity: 'Heteroscedasticity',
  LargeYaxisDataPoints: 'Large Y-axis Data Points',
  Whichplotdoesyourresidual: 'Which plot does your residual plot look most similar to?',
  Perfectyourresidualplot: 'Perfect, your residual plot is randomly distributed. No need to further improve your models.',
  Yourplotisunbalancedonyaxis: 'Your plot is unbalanced on y-axis. You might be able to improve your model via:',
  Lookingforanopportunity: 'Looking for an opportunity to usefully transform your variables, typically your target variable',
  Checkingifyourmodel: 'Checking if your model lacks informative variables',
  Youcantransformorselect: 'You can transform or select variables in our application',
  GotoAdvancedVariableSetting: 'Go to Advanced Variable Setting',
  Alternativelyyoucanmodify: 'Alternatively, you can modify your data offline and reload it.',
  LoadMyNewData: 'Load My New Data',
  DiagnoseResults: 'Diagnose Results:',
  Yourplotisunbalancedonxaxis: 'Your plot is unbalanced on x-axis. You might be able to improve your model via:',
  Lookingforanopportunitytousefully: 'Looking for an opportunity to usefully transform your variables, typically your predictors',
  Checkingifyourmodellack: 'Checking if your model lacks informative variables',
  Youcantransformorselectvariables: 'You can transform or select variables in our application',
  Yourplotishassomeoutliers: 'Your plot is has some outliers. You might be able to improve your model via:',
  Deletingtheoutliers: 'Deleting the outliers if you decide that they are useless',
  Youcandeletetheoutliers: 'You can delete the outliers in our application',
  GotoEdittheFixesforOutliers: 'Go to Edit the Fixes for Outliers',
  Yourplotisnonlinear: 'Your plot is nonlinear. You might be able to improve your model via:',
  Lookingforanopportunityusefully: 'Looking for an opportunity to usefully transform a variable.',
  Checkingifyourneedtoaddnewavariable: 'Checking if your need to add new a variable',
  Yourplotisheteroscedasticity: 'Your plot is heteroscedasticity. You might be able to improve your model via:',
  Yourplothaslargeyaxisdatapoints: 'Your plot has large y-axis datapoints. You might be able to improve your model via:',
  Acceptable: 'Acceptable',
  NotAcceptable: 'Not Acceptable',


  /**
   * /app-bff/src/components/Modeling/Error
   */
  TrainingFailed: 'Training Failed',
  AbortTraining: 'Abort Training',

  // /app-bff/src/components/Modeling/Result
  SimplifiedView: 'Simplified View',
  AdvancedView: 'Advanced View',
  DeployTheModel: 'Deploy the Model',

  ///app-bff/src/components/Modeling/Result
  Predict: 'Predict',
  Units: 'units',
  BenefitCost: 'Benefit Cost',
  Recommended: 'Recommended',
  ModelingResult: 'Modeling Result',
  SelectedModel: 'Selected Model',
  Target: 'Target',
  Selectyourmodelbasedonyourown: 'Select your model based on your own criteria:',
  R2LearnsDefaultSelection: 'R2 Learn\'s Default Selection',
  Input: 'Input:',
  Pleaseenterbenefitandcostin: 'Please enter benefit and cost in the range of 0.00 to 1,000,000,000.00. The number entered can have 2 decimal places max. Both the benefit and cost inputs must be in positive values.',
  Noteifacorrectpredictionbringsyouprofit: 'Note: if a correct prediction brings you profit, it is a benefit. If an incorrect prediction brings you loss, it is a cost. All inputs should be measured in the same units.',
  Tips: 'Tips',
  Benefit: 'Benefit:',
  Cost: 'Cost:',
  Benefits: 'Benefit',
  Costs: 'Cost',
  Recordswithadistributionof: 'records with a distribution of',
  Theoptimalthreshold: 'The optimal threshold:',
  Submit: 'Submit',
  Return: 'Return',
  Benefitcostiscalculated: 'Benefit cost is calculated according to the formula:',
  BenefitTPBenefit: 'Benefit * TP+ Benefit * TN - Cost * FN – Cost * FP ；',
  TPTruePositiveTNTrueNegative: 'TP (True Positive), TN (True Negative), FN (False Negative) and FP (False Positive) is determined depending on the chosen threshold.  A threshold is a critical probability which divides the prediction results into an event group (e.g. will default on loan) and non-event group (e.g. will not default no loan). Typically, a prediction result (probability) that is larger than the threshold goes into the event group, and a prediction result that is smaller than the threshold goes into the non-event group. An optimally defined threshold is one that maximizes the benefit cost.',
  Example: 'Example:',
  Inthisloandefaultexample: 'In this loan default example, “yes” represents that the customer will default on loan and “no” represents that the customer will not default. Assume the following business scenario:',
  Acorrectpredictionof: 'A correct prediction of the default case will save the bank $200K on average',
  Acorrectpredictionofnondefault: 'A correct prediction of the non-default case will allow the bank to make $100K profit on average',
  Anincorrectpredictionofthedefault: 'An incorrect prediction of the default case will cause the bank to lose $200K on average',
  Andanincorrectpredictionofthenondefault: 'And an incorrect prediction of the non-default case will cause the bank to lose $100K profits',
  Youcaninputthisinformationinto: 'You can input this information into the table below using $K as the unit (or $ as the unit):',
  R2Learnwillfindtheoptimalthreshold: 'R2 Learn will find the optimal threshold',
  Thatoptimizesthebenefit: 'that optimizes the benefit:',
  Currentbenefitcostequals: 'Current benefit cost equals:',
  Actual: 'Actual',
  Predicted: 'Predicted',
  Different: 'Different',
  Areaunderthecurve: 'Area under the curve, a popular metric to measure the performance of a classification model. The AUC value typically lies between 0.5 to 1 where 0.5 denotes a bad classifier and 1 denotes an excellent classifier.',
  PerformanceAUC: 'Performance (AUC)',
  Compute: 'Compute',
  TrainingNewModel: 'New Model Being Trained',
  RecommendedAModel: 'We have recommended a model by default.',

  // /app-bff/src/components/Modeling/Result
  PredictedVSActualPlotSorted: 'Predicted VS Actual Plot (Sorted)',
  Howwastheplotcreate: 'How was the plot created?',
  Sortthedatabythe: '1. Sort the data by the actual target value',
  Dividealldatapoints: '2. Divide all data points evenly into 100 groups',
  Calculatethemeanvalue: '3. Calculate the mean value of predicted target values and the actual target values of each group and plot it on the graph',
  HowdoIinterprete: 'How do I interprete it?',
  Weaimtogetyouasense: ' We aim to get you a sense of how accurate the model is by comparing the predicted V.S actual value. Also you may find some pattern.',
  PredictedValues: 'Predicted Values',
  ActualValues: 'Actual Values',
  GoodnessofFit: 'Goodness of Fit',

  // /app-bff/src/components/Modeling/Start
  EasyAndSimple: 'Easy and Simple',
  EasyAndSimpleTip: 'If you want R2 Learn to build the model automatically.',
  AutomaticModeling: 'Automatic Modeling',
  DetailedAndAdvanced: 'Detailed and Advanced',
  DetailedAndAdvancedTip: 'If you want to have more control over the modeling process.',
  AdvancedModeling: 'Advanced Modeling',
  Youneedtoselectatleast: 'You need to select at least one algorithm!',
  Setting: 'Setting',
  PrepareToModel: "Data looks good now. It's time to train your model!",
  AdvancedVariable: 'Advanced Variable',


  // /app-bff/src/components/Modeling/Start
  Histogram: 'Histogram',
  DataType: 'Data Type',
  Mean: 'Mean',
  UniqueValue: 'Unique Value',
  Min: 'Min',
  Max: 'Max',
  CreateVariableListTip: 'You can use check box to create your own variable list.',
  CurrentVariableList: 'Current Variable List',
  AllVariables: 'All Variables',
  Informatives: 'informatives',
  CreateANewVariable: 'Create a New Variable',
  CheckCorrelationMatrix: 'Check Correlation Matrix',
  UnivariantPlot: 'Univariant Plot',
  UnivariantPlots: 'Mosaic Plot',
  Importance: 'Importance',
  AdvancedModelingImportanceTip: 'The following column reflects the importance of the predictor to the target variable.',
  STD: 'STD',
  Median: 'Median',
  Nameisempty: 'name is empty',
  Newvariable: 'new variable',
  Isexist: 'is exist',
  Namecannotcontain: 'name cannot contain _',
  Expressionisempty: 'expression is empty',
  Toomanyfunctions: 'too many functions',
  Unexpectedtoken: 'Unexpected token )',
  Emptyexpression: 'empty expression',
  Errorexpression: 'error expression',
  Unexpectedidentifier: ' Unexpected identifier:',
  Unknownvariable: 'unknown variable:',
  Emptyparameter: 'empty parameters',
  ParametersmustbeNumerical: 'parameters must be Numerical',
  ParametersmustbeCategorical: 'parameters must be Categorical',
  Mustbeinteger: 'must be integer',
  Function: 'function',
  Parameterserror: 'parameters error',
  Mustgreaterthan: 'must greater than',
  Mustlessthan: 'must less than',
  Isnotsupported: 'is not supported',
  Mustbenumber: 'must be number',
  Unexpectedtoken$: 'Unexpected token $',
  Concat: 'Concat()',
  Concatfunctionallowsyou: 'Concat function allows you to easily construct new variables by combine certaininter dependent variables (e.g. variables that describe the same object)',
  Syntax: 'Syntax:',
  Concatvar1: 'Concat(@var1, @var2, @var3,...p1, p2...)',
  Var1var2var3: 'var1, var2, var3... – 2 or more numerical or categorical variables to be combined; the combination order are decided by the input order. All variables need to start with@.',
  Numberofvariables: 'p1, p2... - Number of variables in each combination; its number must be larger than 1 but cannot be larger than the number of specified variables; combinations of p1 variables are created, then combinations of p2 variables are created, and so on.',
  Output: 'Output:',
  Categoricalvariables: '1 or more categorical variables',
  Examples: 'Examples:',
  Concatcolor: 'Concat(@color, @theme, @size, 2)',
  Concatolor3: 'Concat(@color, @theme, @size, 3)',
  Concat23: 'Concat(@color, @theme, @size, 2, 3)',
  Notice: 'Notice:',
  Iftoomanynewvariablesarecreated: 'If too many new variables are created, system will possibly be out of memory. The total number of the created new variables is suggested to be less than 10 times of the number of the original variables.',
  Diff: 'Diff()',
  Difffunctionallowsyoutoeasily: 'Diff function allows you to easily construct new variables by calculating the difference between two rows of selected variables.',
  DIffrow1: 'DIff(@var1, @var2, @var3,...row1,row2,...)',
  Ormorenumericalvariables: 'var1, var2, var3... – 1 or more numerical variables to be calculated the difference; All variables need to start with@.',
  Distancetobecalculated: 'row1,row2,... – distance to be calculated; its number must be equal to or larger than 1 but cannot be larger than the length of the variable(suggestion: larger the row, more missing values).',
  Numericalvariable: '1 or more numerical variables',
  Difftax: 'Diff (@tax, 1,2)',
  Accumulate: 'Accumulate()',
  Accumulatefunction: 'Accumulate function allows you to easily construct new variables by accumulating values from all previous rows.',
  Accumulatevar1var2: 'Accumulate(@var1, @var2, @var3,...)',
  Morenumericalvariables: 'var1, var2, var3... – 1 or more numerical variables to be accumulated; All variables need to start with@.',
  Accumulatedaily_sales: 'Accumulate (@daily_sales, @daily_cost)',
  Iftoomanynewvariablesarecreatedcsystem: 'If too many new variables are created,  will possibly be out of memory.The total number of the created new variables is suggested to be less than 10 times of the number of the original variables.',
  Quantile_bin: 'Quantile_bin()',
  Quantile_binfunctionallows: 'Quantile_bin function allows you to easily construct new variables by dividing selected variables into certain groups depending on its frequency or value.',
  Quantile_binvar1var2: 'Quantile_bin(@var1, @var2, @var3,b, type1, type2)',
  Allvariablesneedtostartwith: 'var1, var2, var3... – 1 or more numerical variables to be divided; All variables need to start with@.',
  Numberofgroupstobedivided: 'b – number of groups to be divided; its number must be greater than 1 but cannot be larger than the length of the variable(suggestion: many groups are meaningless)',
  Type1type2: 'type1,type2 – ways to dividing the variables; 0 and 1 are supported.',
  Variableisdividedbyitspercentile: '0: variable is divided by its percentile, each group is thesame size;',
  Eachgroupiswiththesamevaluerange: '1: variable is divided by its value, each group is with the same value range.',
  Quantile_binage: 'Quantile_bin(@age, 3, 1)',
  Quantile_binage1: 'Quantile_bin(@age1, @age2, 4, 1, 0))',
  Custom_Quantile_bin: 'Custom_Quantile_bin()',
  Custom_Quantile_binfunction: 'Custom_Quantile_bin function allows you to easily construct new variables by dividing selected variables into certain groups depending on customized range.',
  Custom_Quantile_binrange_list1: 'Custom_Quantile_bin(@var, [range_list1], [range_list2]...)',
  Custom_Quantile_binage: 'Custom_Quantile_bin(@age,[25|50],[20|40|60])',
  Interactive: 'Interactive()',
  Interactive_descr: 'Interactive function allows you to construct new variables by mutiplying two of them.',
  Interactiverange_grammar: 'Interactive(@var1, @var2, @var3, …)',
  Interactive_input: 'var1, var2, var3, ….- numerical variable, needs to start with @; maximum of 20 variables is supported.',
  Interactive_output: 'numerical variable',
  Interactive_example: 'Interactive(@age, @income)',

  // /app-bff/src/components/Modeling/Start
  Oneoftheclasseshasnumber: 'One of the classes has number of data points smaller than',
  Pleaseselectalowerfoldcv: 'fold, please select alower fold cv.',
  YourAdvancedModeling: 'Your Advanced Modeling Setting is reset.',
  SelectFromPreviousSettings: 'Select From Previous Settings',
  NameYourModelSettings: 'Name Your Model Settings',
  SpecifytheNumberofClusterstoForm: 'Specify the Number of Clusters to Form:',
  SelectAlgorithm: 'Select Algorithm',
  SelectAll: 'Select All',
  DeselectAll: 'Deselect all',
  SelectDefault: 'Default',
  R2solutionModelling: 'R2-solution-a & b are mandatory modelling algorithms for Advanced Modelling.',
  R2solutiona: 'R2-solution-a',
  R2solutionb: 'R2-solution-b',
  ResamplingSetting: 'Resampling Setting:',
  Autoupsampling: 'Auto upsampling',
  Autodownsampling: 'Auto downsampling',
  Noresampling: 'No resampling',
  SetMeasurement: 'Set Measurement',
  RandomSeed: 'Random Seed',
  ValueBetween: 'Value between',
  SetModelEnsembleSize: 'Set Model Ensemble Size',
  SetModelEnsembleSizeTip: 'Actual number of ensemble models may be less than this number.',
  RunModelsWith: 'Run models with',
  Performingcrossvalidation: 'Performing cross validation on large dataset will take significant amount of time.',
  Hencewerecommendchoosing: 'Hence we recommend choosing “Train Validation Holdout”.`',
  CrossValidation: 'Cross Validation',
  TrainValidationHoldout: 'Train / Validation / Holdout',
  SetPercentage: 'Set Percentage of Each Part',
  SelectNumberofCVfolds: 'Select Number of CV folds',
  SpeedVSAccuracy: 'Speed VS Accuracy',
  Speed: 'Speed',
  Selectavariableasreference: 'Select a variable as reference',

  //app-bff/src/components/Modeling/Start/Preview
  TotalVariables: 'Total Variables',
  ViewDataTable: 'View Data Table',


  //app-bff/src/components/Problem
  Topredictifaneventislikely: 'To predict if an event is likely to happen or not (e.g. if a customer will make a purchase or not).',
  Topredictacontinuous: 'To predict a continuous/numeric value (e.g. cost of a purchase)',
  ChooseProblemType: 'Choose Problem Type',
  Prediction: 'Prediction',
  Predictions: 'Prediction',

  //app-bff/src/components/Project
  ProjectN: 'project name',
  ProblemStatement: 'Problem Statement',
  Predictimportantcustomers: 'e.g. Predict important customers who might churn in the next 30 days so that customer service department can take effectively target and retain these customers.',
  Thiswillhelpproactively: 'e.g. This will help proactively retain important customers. Acquiring a new customer is not costlier than retain an existing customer. It is critial to maintain customer satisfaction and loyalty to sustain good revenue opportunity and a strong market presence.',
  BusinessValue: 'Business Value',


  // app-bff/src/components/Suppor
  R2LearnTutorialVideo: 'R2-Learn Tutorial Video',
  Reportsuccess: 'report success',
  Reporterror: 'report error',
  Overview: '1.Overview',
  Machinelearning: 'Machine learning',
  MachinewithR2: 'Machine learning with R2-Learn',
  GettingstartedwithR2: '2. Getting started with R2-Learn',
  Softwarerequirements: 'Software requirements',
  ImportingdataR2: 'Importing data into R2-Learn',
  Importingdatadatabase: 'Importing data from a database',
  Importinglocalfile: 'Importing a local file',
  Projecthome: 'Project home',
  HomepageDeployment: 'Homepage – Deployment Console',
  Startingproject: '3.Starting a new project',
  Createproject: 'Create a project',
  Chooseyourproblem: 'Choose your problem type',
  Workingwithyour: 'Working with your data',
  DataConnect: 'Data Connect',
  DataSchema: 'Data Schema',
  DataQuality: 'Data Quality',
  CommonIssues: 'Common Issues with Data',
  TargetVariableQuality: 'Target Variable Quality',
  PredictorVariablesQuality: 'Predictor Variables Quality',
  Buildingyourmodelg: 'Building your modelg',
  Predictwithdata: 'Predict with data source',
  Deployingyourmodels: '4.Deploying your models',
  Monitoryourdeployed: 'Monitor your deployed models',
  AppendixQuality: 'Appendix A: Data Quality Fixes',
  Fixingoutliers: 'Fixing outliers',
  Fixingmissingvalues: 'Fixing missing values',
  Fixingdatamismatch: 'Fixing data type mismatch',
  AppendixAdvancedModeling: 'Appendix B: Advanced Modeling',
  AdvancedVariableSettings: 'Advanced Variable Settings',
  AdvancedModelingSetting: 'Advanced Modeling Setting',
  ModelSettingdefault: 'Create/Edit Model Setting By default',
  SetMaxModelEnsemble: 'Set Max Model Ensemble Size',
  TrainValidationHoldoutValidation: 'Train Validation Holdout and Cross Validation',
  SetMeasurementMetric: 'Set Measurement Metric',
  SetSpeedvsAccuracy: 'Set Speed vs Accuracy',
  AppendixModelselection: 'Appendix C: Model selection for Binary Classification problems',
  Simplifiedview: 'Simplified view',
  TableofModels: 'Table of Models',
  AdditionalModelDetails: 'Additional Model Details',
  AppendixModelselectionD: 'Appendix D: Model selection for Regression problems',
  AskQuestion: 'Ask a Question',
  RequestFeature: 'Request a Feature',
  ReportBug: 'Report a Bug',
  UserManual: 'User Manual',
  TutorialVideo: 'Tutorial Video',


  //app-bff/src/components/Upgrade
  NumberofUsers: 'Number of Users',
  NumberofModels: 'Number of Models',
  NumberofPredictions: 'Number of Predictions Storage Space',
  NumberConcurrentProjects: 'Number of Concurrent Projects',
  DataFormat: 'Data Format',
  APIAccess: 'API Access',
  ResourcePriority: 'Resource Priority',
  TechnicalSupport: 'Technical Support',
  Fivemonth: '15/month',
  TWOmonth: '20,000/month',
  No: 'No',
  Low: 'Low',
  Email: 'Email',
  Fivemonths: '150/month',
  TWOmonths: '200,000/month',
  Medium: 'Medium',
  BuyNow: 'Buy Now',
  Ifyouenjoyour: 'If you enjoy our R2 Learn experience and are interested in product upgrade, please choose the SaaS Offering option, and click on the ‘buy now’ button to start!',
  Thetwonewpasswords: 'The two new passwords you entered were inconsistent',
  Passwordchangesucceeded: 'Password change succeeded! Please use your new password to log in.',
  Passwordchangefailed: 'Password change failed, please try later.',
  ChangeYourPassword: 'Change Your Password',
  Pleaseenteryourcurrent: 'Please enter your current password and your new password below.',
  CurrentPassword: 'Current Password',
  NewPassword: 'New Password',
  ConfirmYour: 'Confirm Your New Password',
  ResetYourPassword: 'Reset Your Password',
  Wehavesent: 'We have sent a reset password email to',
  Pleaseclickthereset: 'Please click the reset password link to set your new password.',
  Didnreceivetheemail: 'Didn\'t receive the email yet? Please check your spam folder, or',
  Resend: 'resend',
  Theemail: 'the email',
  ForgetPassword: 'Forget Password',
  Pleaseenteryouremail: 'Please enter your email address you registered with us, and we\'ll send you instruction on how to reset your password',
  EmailAddress: 'Email Address',
  Send: 'Send',
  Passwordresetsuccessed: 'Password reset successed.',
  Pleaseenteryour: 'Please enter your new password below to reset.',
  EnterNewPassword: 'Enter a New Password',
  ConfirmPassword: 'Confirm Password',
  ResetPassword: 'Reset Password',
  Enteryouremail: 'Enter your email',
  Enteravaildemial: 'Enter a vaild emial address',
  SignIn: 'Sign In',
  SetPassword: 'Set a Password',
  Enteryourpassword: 'Enter your password',
  Passwordsnotmatch: 'passwords not match',
  SignUp: 'Sign Up',
  Unavailable: 'Unavailable',
  FreeTrial: 'Free Trial',
  Basic: 'Basic',
  Essential: 'Essential',
  Enterprise: 'Enterprise',
  ByclickingSign: 'By clicking Sign Up,you agree to our',
  EndUserLicense: 'End User License Agreement',
  Alreadyhaveanaccount: 'Already have an account',

  // /app-bff/src/components/UserInfo
  Pleaseloginagain: 'please login again!',
  Used: 'Used',
  TOTAL: 'total',
  LEFT: 'Remaining',
  CONCURRENT_TITLE: 'No. of Projects',
  DEPLOY_TITLE: 'No. of Predictions',
  PROJECT_TITLE: 'No. of Modeling',
  STORAGE_TITLE: 'Storage Space',
  MONTHLY_SUBSCRIPTION_USD_NAME: 'Monthly Subscription (USD)',
  MONTHLY_SUBSCRIPTION_RMB_NAME: 'Monthly Subscription (RMB)',
  ANNUAL_SUBSCRIPTION_USD_NAME: 'Annual Subscription (USD)',
  ANNUAL_SUBSCRIPTION_RMB_NAME: 'Annual Subscription (RMB)',
  RESOURCE_PRIORITY_NAME: 'Resource Priority',
  NUMBER_OF_USERS_NAME: 'Number of Users',
  MODELING_DATA_SIZE_NAME: 'Modeling Data Size',
  NUMBER_OF_CONCURRENT_PROJECTS_NAME: 'No. of Projects',
  NUMBER_OF_PROJECTS_NAME: 'No. of Concurrent Projects',
  NUMBER_OF_MODEL_TRAINING_RUNS_NAME: 'No. of Modeling',
  ADDITIOANL_MODEL_TRAINING_RUNS_USD_NAME: 'Additional Model Training Runs (USD)',
  ADDITIOANL_MODEL_TRAINING_RUNS_RMB_NAME: 'Additional Model Training Runs (RMB)',
  DATA_SOURCE_SUPPORT_NAME: 'Data Source Support',
  STORAGE_SPACE_NAME: 'Storage Space',
  NUMBER_OF_PREDICTIONS_INCLUDED_NAME: 'No. of Predictions',
  ADDITIONAL_PREDICTIONS_USD_NAME: 'Additional Predictions (USD)',
  ADDITIONAL_PREDICTIONS_RMB_NAME: 'Additional Predictions (RMB)',
  API_ACCESS_NAME: 'API Access',
  TECH_SUPPORT_NAME: 'Tech Support',
  UNLIMITED: 'Unlimited',
  UNAVAILABLE: 'Unavailable',
  FREE_TRAIL: 'Free Trial',
  BASIC: 'Basic',
  ESSENTIAL: 'Essential',
  ENTERPRISE: 'Enterprise',
  FORMAT_YEAR: 'MM/DD/YYYY',
  DEADLINE: 'Expiry Date',
  CREATE_TIME: 'Start Date',


  Database: 'Database',


  DataSource: 'Data Source',


  DataNotFound: 'data not found',

  DeploymentOption: 'Deployment Option',
  DeploymentNotFound: 'deployment not found',


  SearchProject: 'Search your project',


  TokenNotFound: 'token not found',


  ValidationDataDefinition: 'Validation Data Definition',
  TrueorFalseBinaryClassification: 'True or False (Binary Classification)',
  ContinuousValuesRegression: 'Continuous Values (Regression)',
  Upgrade: 'Upgrade',
  Header: 'NormalHeader.tsx',
  Row: 'Row',
  Yes: 'Yes',
  Nop: 'No',
  PossibleReasons: 'Possible Reasons',
  Itsthewrongtargetvariable: 'It’s the wrong target variable',
  ReselectTargetVariable: 'Reselect Target Variable',
  Itsgeneraldataqualityissue: 'It’s general data quality issue',
  Thetargetvariablehassomenoise: 'The target variable has some noises',
  Fixit: 'Fix it',
  ChangeTargetVariableValue: 'Change Target Variable Value',
  RemapTarget: 'Remap Targe',
  TargetVariableUniqueValue: 'arget Variable Unique Value',
  YourUniqueValue: 'Your Unique Value',
  AllDatatotalRawLinesrows: 'All Data',
  Rowsminimum: '1000 rows (minimum)',
  Datasize: 'Data size',
  Rowsisrecommended: '1000 rows is recommended',
  Dataissuesarefound: 'Data issues are found',
  MissingValueS: 'Missing Value',
  mismatch: 'Data Type Mismatch',
  outlierRow: 'Outlier',
  CleanDataS: 'Clean Data',
  R2Learnwillfixtheseissuesautomatically: 'R2 Learn will fix these issues automatically',
  EdittheFixes: 'Edit the Fixes',
  Datasizewillbesmallerthantheminimumsizeafterdelete: 'Data size will be smaller than the minimum size after delete',
  Pleaseselecttwovalid: 'Please select two valid values from all unique values in your target variable',
  Selectallvaluesthatmatchas: 'Select all values that match as',
  MATAHC: '',
  Matchas: 'Match as ',
  Therestvalueswillbedeletedbydefault: 'The rest values will be deleted by default.',
  Thankyouforfixingddatassues: 'Thank you for fixing data issues.',
  Thechangeswillnotshowupuntil: 'The changes will not show up until they are applied in training section',
  Back: 'Back',
  Next: 'Next',
  VariableName: 'Variable Name',
  QuantityofMismatch: 'Quantity of Mismatch',
  MostFrequentValue: 'Most Frequent Value',
  Fix: 'Fix',
  Replacewithmostfrequentvalue: 'Replace with most frequent value',
  Deletetherows: 'Delete the rows',
  Replacewith: "Replace with ",
  Replacewithauniquevalue: 'Replace with au nique value',
  Replacewithmeanvalue: 'Replace with mean value',
  Replacewithminvalue: 'Replace with min value',
  Replacewithmaxvalue: 'Replace with max value',
  Replacewithmedianvalue: 'Replace with median value',
  ReplaceWith0: 'Replace With 0',
  Replacewithothers: 'Replace with others',
  MissingReason: 'Missing Reason',
  QuantityofMissingValue: 'Quantityof Missing Value',
  Idonknow: "I don`t know",
  Leftblankonpurpose: 'Left blank on purpose',
  FailedtoCollectorDataError: 'Failed to Collect or Data Error',
  ValidRange: 'Valid Range',
  QuantityofOutlier: 'Quantity of Outlier',
  DoNothing: 'Do Nothing',
  Apply: 'Apply',
  Found: 'Found',
  YourtargetvariableHas: 'Your target variable has',
  Less: 'less',
  More: 'more',
  Thantwouniquealues: ' some noises',
  onlyOnevalue: 'only one unique value',
  Targetvariablequalityisgood: 'Target variable quality is good!',
  Optional: 'optional',
  After: 'After',
  DeploymentpagewillprovidedeploymentIdandtokenparameter: 'Deployment page will provide deploymentId and token parameter',
  Response: 'Response',
  predictresult: 'result:predict result',
  errorcodeifsuccess: 'code:error code, 10000 if success',
  humenreadableinformation: 'message:humen readable information',
  originalerrorinformation: 'error:original error information, this field only exist if some error appear',
  dataisnotavalidJSONstring: 'data is not a valid JSON strin',
  dataisemptyor: 'data is empty or not a valid array',
  fileuploaderror: 'file upload error',
  fileuploaFrror: 'file upload failed',
  predicterror: 'predict error',
  predictf: 'predict failed',
  invalidtoken: 'invalid token',
  exceedpredictionusageimit: 'exceed prediction usage limit',
  exceedpredictionapiimit: 'exceed prediction api limit',
  downloadpredictesultfailed: 'download predict result failed',
  predictresultisempty: 'predict result is empty',
  Yourcsvdata: 'Your csv data',
  DataImport: 'Data Import',
  Kindly_Reminder: 'Kindly_Reminder',
  Change: 'Change',
  Ifyoucanestimatethebusiness: 'If you can estimate the business benefit of a correct prediction and the business cost of an incorrect prediction, we can help you optimize the model parameter or select a more appropriate model.',
  Basedonyourbizscenario: 'Based on your biz scenario,',
  EventDistribution: 'Event Distribution: ',
  A: 'A.',
  B: 'B.',
  Resultbasedonthedataset: 'Result based on the data set with a distribution of',
  Events: 'events:',
  Theoverallbenefit: 'The overall benefit:',
  Boththebenefitandcost: 'Both the benefit and cost input ranges from 0.00 to 1,000,000,000.00.',
  Eventdistributioninputranges: 'Event distribution input ranges from 0.00 to 100.00.',
  NoteAllinputsentered: 'Note：All inputs entered can have 2 decimal places max.',
  Eventdistributionistheproportion: 'Event distribution is the proportion of the event (e.g. will default on loan) in the whole data set. Benefit and cost value will be affected by the distribution. Higher the event distribution higher the benefit and cost value for the event, and the opposite is true for the non-event group. The relation is explained in the formula above, where',
  Isthedefaulteventdistribution: 'is the default event distribution based on the uploaded training  data set and',
  Istheuserprovideddistribution: 'is the user provided distribution based on actual business scenario.',
  Thedistributionof: 'The distribution of “yes” from the uploaded data is 10%, but the user thinks the actual distribution of default case is around 20%',
  R2Learnthenautomaticallyfinds: 'R2 Learn then automatically finds a model with the optimal threshold ',
  Thatmaximizethebenefit: 'x that maximize the benefit.',
  Yourusageofmodelingdata: 'Your usage of modeling data size has reached the max restricted by your current license.',
  Missingparams: 'missing params',
  Modelingfiletoolarge: 'modeling file too large',
  Storagespacefull: 'storage space full',
  Uploaderror: 'upload error',
  Resettodefault: 'Reset to default',
  FX: 'fx',
  NAME: 'name',
  ADD: 'Add',
  Average: 'Average',
  PointNumber: 'Group ID',
  NewAverage: '',
  RawData: 'Raw Data',
  GroupNumber: 'Group Number:',
  PredictedAverage: 'Predicted Average:',
  ActualAverage: 'Actual Average:',
  DataPreprocessing: 'Data Preprocessing',
  FeaturePreprocessing: 'Feature Preprocessing',
  ModelTraining: 'Model Training',
  RootMeanSquareErrorRMSEmeasures: 'Root Mean Square Error (RMSE) measures prediction errors of the model. Normalized RMSE will help you compare model performance: the smaller the better.',
  Problemstatement: 'Problem statement ',
  Businessvalue: 'Business value ',
  SpeedvsAccuracy: 'Speed vs Accuracy',
  LiftsCharts: 'Lifts Charts',
  ROCCurves: 'ROC Curves',
  Speedms1000rows: 'Speed(s/1000rows)',
  Percentage: 'Percentage',
  TruePositiveRate: 'True Positive Rate',
  FalsePositiveDate: 'False Positive Rate',
  GOOD: 'GOOD',
  Yourusageofnumberofdeploylineshas: 'Your usage of number of deploy lines has reached the max restricted by your current license.',
  Aftercompleted: 'After completed',
  Empty: 'empty',
  Custom: 'custom_',
  Ons: '',
  S: 'S',
  M: 'M',
  T: 'T',
  W: 'W',
  TH: 'T',
  F: 'F',
  SA: 'S',
  Default: 'default',
  CloseDataTable: 'Close Data Table',
  empty: 'empty ',
  NeverS: 'never',
  AdvancellcedModeling: 'Advanced Modeling',
  correctly: 'correctly',
  incorrectly: 'incorrectly',
  price: 'price',
  True: 'True',
  False: 'False',
  Positive: ' Positive',
  Negative: ' Negative',
  UnsupervisedLearning: 'Unsupervised Learning',
  Clustering: 'Clustering',
  OutlierDetection: 'Outlier Detection',
  ProbabilityThreshold: 'Probability Threshold',
  percentage: 'percentage',
  lift: 'lift',
  ProbabilityDensity: 'Probability Density',
  Truevalue: 'True value',
  Predictvalue: 'Predict value',
  Residual: 'Residual',
  EnsembledModel: 'Ensembled Model',
  Onehotencoding: 'One hot encoding',
  Rescaling: 'Rescaling',
  Imputation: 'Imputation',
  Banlance: 'Banlance',
  extremlrandtreesprepr: 'extreml.rand.trees.prepr.',
  ICA: 'ICA',
  FeatureAgglomeration: 'Feature Agglomeration',
  kernelPCA: 'kernel PCA',
  KitchenSinks: 'Kitchen Sinks',
  LinearSVMprepr: 'Linear SVM prepr.',
  NoPreprocessing: 'No Preprocessing',
  NystroemSampler: 'Nystroem Sampler',
  PCA: 'PCA',
  Polynomial: 'Polynomial',
  RandomTreesembed: 'Random Trees embed.',
  SelectPercentile: 'Select Percentile',
  SelectRates: 'Select Rates',
  colortheme: 'color_theme',
  colorsize: 'color_size',
  themesizel: 'theme_size',
  colorthemesize: 'color_theme_size',
  tax: 'tax',
  taxdiffr1: 'tax_diff_r1',
  taxdiffr2: 'tax_diff_r2',
  dailysales: 'daily_sales',
  dailysalesaccum: 'daily_sales_accum',
  dailycost: 'daily_cost',
  dailycostaccum: 'daily_cost_accum',
  age: 'age',
  agevalb3: 'age_val_b3',
  age1valb4: 'age1_val_b4',
  age1freb4: 'age1_fre_b4',
  age2valb4: 'age2_val_b4',
  age2freb4: 'age2_fre_b4',
  agecusb3: 'age_cus_b3',
  agecusb4: 'age_cus_b4',
  ChooseaVariableScalingMethod: 'Choose a Variable Scaling Method',
  minmaxscale: 'min_max_scale',
  robustscale: 'robust_scale',
  FromSQL: 'From SQL',
  ProjectReport: 'Project Report',
  standardscale: 'Standard Scale',
  Hostname: 'Hostname',
  Port: 'Port',
  DatabaseType: 'Database Type',
  TableName: 'Table Name',
  SQLoptional: 'SQL(optional)',
  SQLforquery: 'SQL for query',
  DatabaseEncoding: 'Database Encoding',
  optional: 'optional',
  Username: 'Username',
  Yourdatabaseusername: 'Your database username',
  Password: 'Password',
  Yourdatabasepassword: 'Your database password',
  RememberMyPassword: 'Remember My Password',
  RememberMyConnectionProfile: 'Remember My Connection Profile',
  CONNECT: 'CONNECT',
  Yourtablename: 'Your table name',
  DatabaseName: 'Database Name',
  Eg: 'eg.,',
  NoteIfapredictionbringsyou: 'Note: If a prediction brings you loss, it is a cost; If a prediction result brings you profit, it is a benefit. All inputs should be measured at the same unit.',
  Exports: 'Export',
  Export: 'Export',
  CostBased: 'Cost Based',
  NotSatisfied: 'NotSatisfied',
  ExportingReport: 'Exporting Report',
  preparingunivariateplot: 'preparing univariate plot.',
  preparinghistogramplot: 'preparing histogram plot.',
  preparingvariabledata: 'preparing variable data.',
  preparingvariablepreimportance: 'preparing variable preimportance.',
  preparingvariablecorrelationmatrix: 'preparing variable correlation matrix.',
  downloadingplots: 'downloading plots.',
  generatingreportfile: 'generating report file',
  init: 'init',
  Weight: 'Weight',
  BeforeETL: 'Before ETL',
  AfterETL: 'After ETL',
  DataQualityIssuesandFixMethod: 'Data Quality Issues and Fix Method',
  SummaryofFixes: 'Summary of Fixes',
  Profile: 'Profile',
  ProjectStatement: 'Project Statement',
  ProblemType: 'Problem Type',
  ExploratoryDataAnalysis: 'Exploratory Data Analysis',
  ModelResult: 'Model Result',
  Metrics: 'Metrics',
  ConfusionMatrix: 'Confusion Matrix',
  Charts: 'Charts',
  VariableImpactnotavailableforthisalgorithm: 'Variable Impact not available for this algorithm',
  SetMaxTrainingTime: 'Set Max Training Time',
  Maxamountoftimetoevaluatedifferentmodules: 'Max amount of time to evaluate different modules.',
  Minutes: 'Minutes',
  minutesorlonger: '5 minutes or longer',
  NoMoreThan: 'No More Than',
  Auto: 'Auto',
  SimpleView: 'Simple View',
  Youcanalsotellusyourbusinessneedstogetamorepreciserecommendation: 'You can also tell us your business needs to get a more precise recommendation',
  ContaminationRate: 'Contamination Rate',
  TheNumberofClusters: 'The Number of Clusters',
  NumberofClusters: 'Number of Clusters',
  Score: 'Score',
  SihouetteScore: 'Sihouette Score',
  exportreporterror: 'export report error.',
  Inputyourcostorbenefitofeveryredictionresult: 'Input your cost or benefit of every prediction result: (0 ~ 100)',
  MappingDictionary: 'Mapping Dictionary',
  Explaination: 'Explaination',
  pleaseenteryourhostname: 'please enter your host name',
  invalidhostport: 'invalid host port',
  invaliddatabasetype: 'invalid database type',
  pleaseenteryourdatabasename: 'please enter your database name',
  pleaseenteryourtablename: 'please enter your table name',
  pleaseenteryourdatabseusername: 'please enter your databse username',
  pleaseenteryourdatabsepassword: 'please enter your databse password',
  PleaseSelectaCategoricalVariable: 'Please Select a Categorical Variable',
  Encoding: 'Encoding',
  Origin: 'Origin',
  Choose2Variables: 'Choose 2 Variables',
  Youcanadjustthecontaminationrate: 'You can adjust the contamination rate',
  Choose2or3Variables: 'Choose 2 or 3 Variables',
  Result: 'Result',
  Ss: 's',
  ScoreHint: 'It evaluates the performance of the model. It ranges from 0 and 1. In general, a larger value indicates better model performance.',
  ContaminationRateHint: 'The proportion of anomaly to all data.',
  CVNNHint: 'It evaluates intercluster separation and the intracluster compactness. It ranges from 0 and 2. In general, a smaller value indicates better model performance.',
  TheNumberofClustersHint: 'TheNumberofClustersHint',
  squaredHint: 'It measures that how much (in percentage) the sample can be separated. It ranges from 0 and 1. In the models with the same number of clusters, a larger value indicates that the model is better.',
  SihouetteScoreHint: 'It validates the clustering performance based on the pairwise difference of between- and within-cluster distances. It ranges from -1 and 1. In general, a larger value indicates better model performance.',
  CHIndexHint: 'It evaluates the cluster validity based on the average between- and within-cluster sum of squares. In general, a larger value indicates better model performance.',
  clustersHint: 'clustersHint',
  RMSSTDHint: 'It measures the homogeneity of the formed clusters. In the models with the same number of clusters, a smaller value indicates that the model is better.',
  clusters: '#clusters',
  ImportantVariables: 'Important Variables',
  Cluster: 'Cluster',
  ClusteringHint: 'To group a set of objects in such a way that objects in the same cluster are more similar to each other than to those in other clusters. (e.g. customer segmentation)',
  OutlierDetectionHint: 'To identify rare events which raise suspicions by differing significantly from the majority of the data. (e.g. Credit Card Fraud Detection)',
  ExplainationHint: 'Important variables for each cluster.',
  DoyouwanttotreatnullL: 'Do you want to treat null values as one class?',
  cannotDeploy: 'Tip: The model you choose only supports deployment of original training data.',
  TargetValues: 'Target Values',
  MissingValues: 'Missing Values',
  KindlyReminder: 'Kindly Reminder',
  Null: '',
  VariableFormula: 'Variable Formula',
  FormField: 'Form Field',
  ProjectDescription: 'Project Description',
  ClusterReason: 'Since all your data predicted by this model belongs to one cluster, the metrics can not be computed.',
  Replacewithlower: 'Replace with lower',
  Replacewithupper: 'Replace with upper',

  Pleaseinputsomecontentsforthesubmissio: 'Please input some contents for the submission.',
  Variablename: 'variable name',
  formula: 'formula',
  Exportmodelresults: 'Export model results',


  ClusterInfReason: 'the value of this metric is overflow',
  DataQualityFixing: 'Data Quality Fixing',
  none: 'None',
  VarianceExplained: 'Variance Explained',
  VarianceExplainedTip: `The table is arranged in descending order of eigenvalues. A larger eigenvalue indicates that the principal component (PC) has more explanatory power. In general, we choose PCs with a accumulated proportion  greater than or equal to 0.8 to represent the entire data.
                        For example: in the following table, we think that the first three PCs are representative enough.<br/>
                         <img src="/VarianceExplainedTip-en.png" alt=""/>
                        `,
  PC: '#PC',
  Eigenvalue: 'Eigenvalue',
  ComulatedProportion: 'Comulated Proportion',
  Choose2PCs: 'Choose 2 PCs',
  Choose2PCsTip: `
                  <section style="height:400px;overflow:auto;">
                   <strong>How to use this feature?</strong><br/>
                  Please select any two PCs. By default, the two most important PCs display.<br/>
                  <strong>At first</strong><br/>
                  The diagram on the left below shows the correlation between the PC and the original variable, which makes it easier to understand the PC.<br/>
                  The following figure is an example:<br/>
                  (1) It can be seen along the x-axis that PC1 and variable x4 are strongly positively correlated, and x6 is strongly negatively correlated. PC1 is dominated by these two variables, and the influence of the remaining variables is slightly weaker.<br/>
                  (2) It can be seen along the y-axis that PC2 is strongly positively correlated with variable x5, PC2 is dominated by it, and the influence of the remaining variables is slightly weaker.<br/>
                   <img src="/Choose2PCsTip1.png" alt=""><br/>
                  <strong>Then</strong><br/>
                  The scatter plot on the bottom right, with the PC you selected as the axis. The results of the clustering are displayed on the graph as points of different colors. You can clearly see what the characteristics of each cluster's sample are.<br/>
                  Combine the above figure, and the following figure is an example:<br/>
                  (1) The first principal component separates the two clusters, so x4 and x6 are the key variables that distinguish the two clusters.<br/>
                  (2) Cluster0 (blue) takes a larger value on PC1, referring to the correlation between the PC and the original variable, which means that the samples with large x4 value and small value of x6 in the original variable is gathered in In this cluster and cluster1(green) is just the opposite.<br/>
                   <img src="/Choose2PCsTip2.png" alt="">
                 </section>
                `,
  PCSTitle: 'The Correlation between PCs and original variables:',
  ScatterPlotOfPCs: 'ScatterPlot of PCs:',
  FeatureCreationSelection: 'Feature Creation & Selection',
  PCAIntro: "PCA (Principal Component Analysis) is a traditional dimensionality reduction method that extracts a few representative principal components (PCs) as representative of high-dimensional data.",
  watchtheinstructionalvideos: 'Would you like to watch the tutorial video?',
  Dontpromptforthismessage: "Do not display this message.",
  YES: 'Yes',
  NO: 'No',
  Logconversionofthe2: 'Logarithmic tranformation with 2 as the base.',
  VarContinuousvariablestartingwiththesymbol: 'var- numerical variable, needs to start with @.',
  Description: 'Note:',
  Negativenumbersinvariableswill0: 'All negative values will be replaced with 0. ',
  Logconversionofthe10: 'Logarithmic tranformation with 10 as the base. ',
  Logconversionofthee: 'Logarithmic tranformation with a natural base e. ',
  Calculatethenthpoweroftheselectedvariable: 'Exponential funcion with var as the base and n as the exponent.',
  Npositiveornegativeintegerordecimal: 'n- real number.',
  Whenthereturnvalueexceedsthememory: 'Values out of the memory will be replaced with the mininum or maximum based on the system.',
  Comparestwovariablesforequality: 'Comparison between two variables, returns 1 when they are equal, 0 when they are unequal.',
  Var1Adiscretevariable: 'var1- numerical or categorical variable, needs to start with @.',
  Var2Adiscretevariable: 'var2- numerical or categorical variable, needs to start with @.',
  Return01result: '0 or 1.',
  Whenasinglevariableisentered: 'When input one variable, output the sum of this variable; when input multiple variables, output the sum of these variables according to the rows.',
  Var1var2var3continuousvariables: 'var1, var2, var3, ….- numerical variable, needs to start with @.',
  Whenasinglevariableisenteredtheminimumvalue: 'When input one variable, output the max of this variable; when input multiple variables, output the max of these variables according to the rows.',
  Whenasinglevariableisenteredtheminimumvaluemax: 'When input one variable, output the minimum of this variable; when input multiple variables, output the minimum of these variables according to the rows.',
  Whenasinglevariableisenteredtheminimumvaluemaxmean: 'When input one variable, output the mean of this variable; when input multiple variables, output the mean of these variables according to the rows.',
  senior: 'R2 custom function',
  base: 'Basic function',
  lidationDataDefinition: 'Required variable name',
  DeploymentOptionText: 'Option',
  Thisratiowilldetermine: 'This ratio will determine the model deployment results',
  normal: 'Normal',
  abnormal: 'Outlier',
  Scaleseachfeaturetothegivenrange: 'Scales each feature to the given range - between zero and one. The Formula is (x - min) / (max - min).',
  Centereachfeaturetothemean: 'Center each feature to the mean and scale to unit variance. The Formula is (x - mean) / std.',
  Centereachfeaturetothemedian: 'Center each feature to the median and  scale according to the interquartile range. The Formula is (x - median) / (75th quantile - 25th quantile).  This method is robust to outliers.',
  Youcangivehigherweightstofeatures: 'You can give higher weights to features that you think are important. The value ranges from 0.1 to 99.9 and the adjustment step is 0.1.',
  restore: 'restore',
  Groupaverage: 'average of group',
  DropTheseVariables: "Drop these Variables",
  CreateTheseVariables: "Create these Variables",
  func_note: 'Note',
  Box_cox: 'Box_cox',
  Box_cox_descr: 'Box_cox function allows you to construct a new variable by Box-Cox transformation with parameter lambda.',
  Box_cox_grammar: 'Box_cox(@var, lambda)',
  Box_cox_input: 'var- numerical variable, needs to start with @.',
  Box_cox_input1: 'lambda- real number; when no lambda is input, the optimal lambda value is defined by maximizing likelihood function as default.',
  Box_cox_output: 'numerical variable',
  Box_cox_example: 'Box_cox(@duration)',
  Box_cox_example1: 'Box_cox(@duration,0.5)',
  Box_cox_note: 'Box_cox(@duration)',
  Box_cox_note_txt: '1. When there are values of the variable less than 0, all values of this variable will be translated into a range greater than or equal to 1.',
  Box_cox_note_txt1: 'Unreasonable lambda can cause errors. The recommended range of it is -5.00~5.00, which supports two decimal places max.',

  Number_extraction: 'Number_extraction',
  Number_extraction_descr: 'Number_extraction function allows you to extract the digital information.',
  Number_extraction_grammar: 'Number_extraction(@var)',
  Number_extraction_input: 'var- categorical variable, needs to start with @.',
  Number_extraction_output: 'numerical variable',
  Number_extraction_note_txt: 'When the variable contains multiple interval numbers, the extracted numbers will be ',
  Number_extraction_example: 'Number_extraction(@percent)',

  Substring: 'Substring',
  Substring_descr: 'Substing function allows you to extract the information of the variable by specifying the position.',
  Substring_grammar: 'Substring(@var1, [position1, position2])',
  Substring_input: 'var- categorical variable, needs to start with @.',
  Substring_input1: 'position1, position2- positive integer, greater than or equal to 0; position1 is the starting position of the extracted variable, and position2 is the ending position; the starting position starts at 0; position2 must be greater than position1.',
  Substring_output: 'categorical variable',
  Substring_note_txt: 'if position2 exceeds the variable length, it will be automatically replaced with the end of the variable.',
  Substring_example: 'Substring(@month, [3, 5])',

  Groupby: 'Groupby',
  Groupby_descr: 'Groupby function allows you perform statistical calculation of selected variable by specifying primary key variables (key).',
  Groupby_grammar: 'Groupby(@var, [@key1, @key2], [fun1,fun2,…])',
  Groupby_input: 'var- numerical or categorical variable, needs to start with @.',
  Groupby_input1: 'key1, key2- categorical variable, primary key variable for grouping the selected variable; maximum of 2 key variables is supported; when only one primary key variable is selected, "[]" can be omitted; all variables input need to start with @.',
  Groupby_input2: 'fun1, fun2,…- statistical function; when only one function is selected, "[]" can be omitted;',
  Groupby_input3: 'when var is a numerical variable, functions [sum, mean, min, max, std, median] are supported;',
  Groupby_input4: 'when var is a categorical variable, function [mode] is supported by default.',
  Groupby_output: 'numerical or categorical variable',
  Groupby_example: 'Groupby(@duration, [@job], [sum, median])',
  Groupby_example1: 'Groupby(@duration, [@job, @education], [mean, min])',
  Groupby_example2: 'Groupby(@job, [@education])',
  Minimum: 'Minimum',
  Maximum: 'Maximum',
  TargetMore2Unique: "Target has more than 2 unique values",
  Areyousuretodeletethismodeldeployment: 'Are you sure to delete this model deployment? This action cannot be recovered.',
  DropTheRows: 'Drop the rows',
  Mapping: "Mapping",
  value: 'value',
  SelectFeature: 'Select Feature Preprocessor',
  errorparams: 'error params',
  ResidualRate: 'Residual Rate',
  ResidualPercent: 'Residual Percent',
  InputRanges: 'Input Ranges',
  ZoomRegion: 'Zoom Region',
  ChartDescription: "Plot Explanation",
  ChartOrder: "1.Target variable is sorted by ascending according to the true value",
  ChartSplit: "2.Sorted date is divided into 100 groups in the selected range",
  ChartSHowWhat: "3.True value, predict value and absolute percentage error are the mean values within each group.",
  ChartZone: "4.Zoom in methods:",
  ChartZoneA: "  a. click ”zoom in“ and hold on to directly choosing the area of the plot",
  ChartZoneB: "  b. input the range of the target variable and click \"ok\"",
  ChartZoneC: "  c. rolling the mouse wheel to zoom in",
  ChartReset: "5.Click \"reset\" to to whole value range",
  custom: "custom function",
  timeoutRetry: "Connection timeout. Reconnecting now.",
  Deployment: 'Deployment',
  PerformanceMonitors: 'Performance Monitor',
  WithinGroupSsSquares: "Within Group SS Squares",
  WithinGroupSsPlot: "Within Group SS Plot",
  WithinGroupsSs: "Within Groups SS",
  ImportantValues: "Median Value of The Variable",
  adjustMutualInfo: 'Adjust Mutual Info',
  adjustRandScore: 'Adjust Rand Score',
  ClusteringTarget: `If your data contains the "Target Variable" , please select. We will evaluate the performance of the clustering models. Otherwise, you can leave blank here.`,
  OutlierTarget: `If your data contains the "Target Variable" , please select. We will evaluate the performance of the outlier detection models. Otherwise, you can leave blank here.`,
  choosecharset: 'choose charset:',
  UTF_8: 'UTF-8(default)',
  UTF_16: 'UTF-16',
  GBK: 'GBK',
  GB_2312: 'GB-2312',
  BIG5: 'BIG5',
  residual:"residual",
};


export default EN_LAN;
